version: '3.8'
services:
  web:
    build:
      context: .
      args:
        - MONGO_URI=${MONGO_URI}
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_APP_CLIENT_ID=${GOOGLE_APP_CLIENT_ID}
      - GOOGLE_APP_CLIENT_SECRET=${GOOGLE_APP_CLIENT_SECRET}
      - WECHAT_PAY_APP_ID=${WECHAT_PAY_APP_ID}
      - WECHAT_APP_SECRET=${WECHAT_APP_SECRET}
      - WECHAT_PAY_MCH_ID=${WECHAT_PAY_MCH_ID}
      - WECHAT_PAY_KEY=${WECHAT_PAY_KEY}
      - WECHAT_PAY_PFX_PATH=${WECHAT_PAY_PFX_PATH}
      - WECHAT_PAY_NOTIFY_URL=${WECHAT_PAY_NOTIFY_URL}
      - ALIYUN_OSS_ACCESS_KEY_ID=${ALIYUN_OSS_ACCESS_KEY_ID}
      - ALIYUN_OSS_ACCESS_KEY_SECRET=${ALIYUN_OSS_ACCESS_KEY_SECRET}
      - ALIYUN_OSS_BUCKET=${ALIYUN_OSS_BUCKET}
      - ALIYUN_OSS_REGION=${ALIYUN_OSS_REGION}
    restart: always
    network_mode: "host"  # 使用主机网络模式，这样可以直接访问服务器上的 MongoDB

networks:
  app-network:
    driver: bridge 
